MacroCalculator/MacroCalculator/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^', include('app_1.urls')),
    #url(r'^app_1/', include('app_1.urls')),
    url(r'^admin/', admin.site.urls),
]

MacroCalculator/app_1/urls.py
from django.conf.urls import url, include
from django.contrib.auth import views as auth_views

from . import views

app_name = 'app_1'

urlpatterns = [
    # ex: /
    url(r'^$', views.home, name='home'),
    # ex: /register/
    url(r'^register/$', views.register, name='register'),
    # ex: /profile/
    url(r'^profile/$', views.index, name='index'),
    # ex: /profile/5/
    url(r'^profile/(?P<user_id>[0-9]+)/$', views.profile, name='profile'),
    # ex: /profile/5/history/
    url(r'^profile/(?P<user_id>[0-9]+)/history/$', views.history, name='history'),
    # ex: /profile/5/add_food
    url(r'^profile/(?P<user_id>[0-9]+)/add_food/$', views.add_food, name='add_food'),
    # ex: /profile/5/add_food/3/delete
    url(r'^profile/(?P<user_id>[0-9]+)/item/(?P<item_id>[0-9]+)/delete$', views.delete_food, name='delete_food'),
    # ex: /profile/5/add_food/4/add_ingredient
    url(r'^profile/(?P<user_id>[0-9]+)/add_food/(?P<item_id>[0-9]+)/add_ingredient$', views.add_ingredient,
        name='add_ingredient'),
    url(r'^profile/(?P<user_id>[0-9]+)/remove_user$', views.remove_user, name='remove_user'),

    url(r'^profile/(?P<user_id>[0-9]+)/objective/$', views.objective, name='objective'),

    url(r'^profile/(?P<user_id>[0-9]+)/modify_profile/$', views.edit_profile, name='edit_profile'),


    # ex: /login
    url(r'^login/$', auth_views.login, {'template_name': 'app_1/login.html'}, name='login'),
    # ex: /logout
    url(r'^logout/$', auth_views.logout, {'next_page': '/'}, name='logout')



]

MacroCalculator/app_1/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import History, Profile, Item
import requests
import json
import sys

class ItemForm(forms.Form):
    name = forms.CharField(label='Name', max_length = 100,required=True)

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user')  # cache the user object you pass in
        super(ItemForm, self).__init__(*args, **kwargs)  # and carry on to init the form


    def clean(self):
    # test the rate limit by passing in the cached user object
        cleaned_data = super().clean()
        name_form = cleaned_data.get('name')
        myHistory = History.objects.filter(usuario=Profile.objects.get(pk=self.user))
        l_items = myHistory.values_list()
        #print("XXXXXXXXXXXXXXXXXXXXXX", file=sys.stderr)
        #print(l_items, file=sys.stderr)
        #print("XXXXXXXXXXXXXXXXXXXXXX", file=sys.stderr)
        for ll in l_items :
            if name_form == Item.objects.get(pk=ll[2]).name :
                ##ERROR
                raise forms.ValidationError(
                        "Food name "+ cleaned_data["name"] +" already exists"
                )
        return self.cleaned_data  # never forget this!

class IngredientsForm(forms.Form):
    ingredient_1 = forms.CharField(label='Ingredient 1', max_length=100,required=True)
    amount_1 = forms.CharField(label='Amount 1', max_length=100,required=True)
    ingredient_2 = forms.CharField(label='Ingredient 2', max_length=100,required=False)
    amount_2 = forms.CharField(label='Amount 2', max_length=100,required=False)
    ingredient_3 = forms.CharField(label='Ingredient 3', max_length=100,required=False)
    amount_3 = forms.CharField(label='Amount 3', max_length=100,required=False)
    ingredient_4 = forms.CharField(label='Ingredient 4', max_length=100,required=False)
    amount_4 = forms.CharField(label='Amount 4', max_length=100,required=False)
    ingredient_5 = forms.CharField(label='Ingredient 5', max_length=100,required=False)
    amount_5 = forms.CharField(label='Amount 5', max_length=100,required=False)
    ingredient_6 = forms.CharField(label='Ingredient 6', max_length=100,required=False)
    amount_6 = forms.CharField(label='Amount 6', max_length=100,required=False)
    ingredient_7 = forms.CharField(label='Ingredient 7', max_length=100,required=False)
    amount_7 = forms.CharField(label='Amount 7', max_length=100,required=False)
    ingredient_8 = forms.CharField(label='Ingredient 8', max_length=100,required=False)
    amount_8 = forms.CharField(label='Amount 8', max_length=100,required=False)
    ingredient_9 = forms.CharField(label='Ingredient 9', max_length=100,required=False)
    amount_9 = forms.CharField(label='Amount 9', max_length=100,required=False)
    ingredient_10 = forms.CharField(label='Ingredient 10', max_length=100,required=False)
    amount_10 = forms.CharField(label='Amount 10', max_length=100,required=False)

    def clean(self):
        form_data = self.cleaned_data
        #Set API
        app_id = "050e8e37"
        api_key = "d0142932f60a692aa1934cb8d9971206"
        url = 'https://trackapi.nutritionix.com/v2/natural/nutrients'
        headers = {'x-app-id': app_id, 'x-app-key': api_key}
        #Call API
        
        ingredient_ix  = "ingredient_X"
        amount_ix = "amount_X"

        for i in range(1,10):
            ingredient_ix = ingredient_ix[:-1]
            ingredient_ix = ingredient_ix + str(i)
            amount_ix = amount_ix[:-1]
            amount_ix = amount_ix + str(i)
            if form_data[ingredient_ix] :
                val = form_data[ingredient_ix] + ' ' + form_data[amount_ix]
                if val != "" :
                    payload = {'query': val}
                    consulta_raw = requests.post(url, headers=headers, data=payload).text
                    consulta_dec = json.loads(consulta_raw)
                    #   
                    if "message" in consulta_dec and consulta_dec['message'] == "We couldn't match any of your foods" :
                        raise forms.ValidationError(
                            "Ingredient "+str(i)+" doesn't match any known ingredient"
                        )

        return form_data



class ObjectivesForm(forms.Form):
    calories = forms.IntegerField(label="calories", max_value=15000, required=True)


class RegisterForm(UserCreationForm):
    date_birth = forms.DateField(help_text='Required. Format: YYYY-MM-DD')
    country = forms.CharField(max_length=30)
    city = forms.CharField(max_length=30)
    cp = forms.IntegerField(help_text='Zip code')
    tags = forms.CharField(max_length=180)

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2',)


class EditProfileForm(forms.Form):
    #user = instance.id
    #TODO: ver cómo poner valores iniciales
    date_birth = forms.DateField()
    country = forms.CharField(max_length=30)
    city = forms.CharField(max_length=30)
    cp = forms.IntegerField()
    tags = forms.CharField(max_length=180)

MacroCalculator/app_1/views.py
from django.shortcuts import get_object_or_404, render
# Create your views here.
from django.http import HttpResponse, HttpResponseRedirect
from django.utils import timezone
from .models import Profile, Ingredient, Item, History, Objective
from .forms import ItemForm, IngredientsForm, RegisterForm, EditProfileForm,ObjectivesForm
import requests
import json
from django.contrib.auth import login, authenticate
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from decimal import Decimal
import sys
from django import forms

def home(request):
    return render(request, 'app_1/home.html')


def index(request):
    userid = request.user.id
    return redirect('app_1:profile', user_id=userid)


def profile(request, user_id):
    user = get_object_or_404(User, pk=user_id)
    return render(request, 'app_1/user_prof.html', {'user': user})


def add_food(request, user_id):
    if request.method == 'POST':  # si el usuario está enviando el formulario con datos
        form = ItemForm(request.POST, user=request.user)  # Bound form
        if form.is_valid():
            new_item = Item(name = form.cleaned_data['name'])
            new_item.save()  # Guardar los datos en la base de datos
            url = str(new_item.id) + '/add_ingredient'
            return HttpResponseRedirect(url)
    else:
        form = ItemForm(user=request.user)  # Unbound form

    return render(request, 'app_1/item_form.html', {'form': form, 'user_id': user_id})

def delete_food(request, user_id, item_id):
    obj = get_object_or_404(Item, pk=item_id)
    obj.delete()
    return HttpResponseRedirect("/profile/" + user_id + "/history")

def add_ingredient(request, user_id, item_id):
    if request.method == 'POST':  # si el usuario está enviando el formulario con datos
        form = IngredientsForm(request.POST)  # Bound form
        if form.is_valid():

            user = Profile.objects.get(pk=user_id)
            prev_item = Item.objects.get(pk=item_id)
            calories_acum = prev_item.calories
            fat_acum = prev_item.tot_fat
            protein_acum = prev_item.tot_protein
            sugar_acum = prev_item.sugar
            carbs_acum = prev_item.tot_carbs
            sat_fat_acum = prev_item.fat_saturated
            fiber_acum = prev_item.fiber
            sodium_acum = prev_item.sodium

            app_id = "050e8e37"
            api_key = "d0142932f60a692aa1934cb8d9971206"
            url = 'https://trackapi.nutritionix.com/v2/natural/nutrients'
            headers = {'x-app-id': app_id, 'x-app-key': api_key}

            # ·INGREDIENTE 1
            val = form.cleaned_data['ingredient_1'] + ' ' + form.cleaned_data['amount_1']
            payload = {'query': val}
            consulta_raw = requests.post(url, headers=headers, data=payload).text
            consulta_dec = json.loads(consulta_raw)
            if "foods" in consulta_dec:
                calories_acum += consulta_dec["foods"][0]["nf_calories"]
                fat_acum += consulta_dec["foods"][0]["nf_total_fat"]
                protein_acum += consulta_dec["foods"][0]["nf_protein"]
                sugar_acum += consulta_dec["foods"][0]["nf_sugars"]
                carbs_acum += consulta_dec["foods"][0]["nf_total_carbohydrate"]
                sat_fat_acum += consulta_dec["foods"][0]["nf_saturated_fat"]
                fiber_acum += consulta_dec["foods"][0]["nf_dietary_fiber"]
                sodium_acum += consulta_dec["foods"][0]["nf_sodium"]
                ingredient_store = Ingredient(item=prev_item, name=form.cleaned_data['ingredient_1'],
                                              amount=form.cleaned_data['amount_1'])
                ingredient_store.save()

            ingredient_ix  = "ingredient_X"
            amount_ix = "amount_x"

            for i in range(2,11):
                ingredient_ix = ingredient_ix[:-1]
                amount_ix = amount_ix[:-1]
                ingredient_ix = ingredient_ix + str(i)
                amount_ix = amount_ix + str(i)
                #if form.cleaned_data[ingredient_ix] and form.cleaned_data[amount_ix]:
                val = form.cleaned_data[ingredient_ix] + ' ' + form.cleaned_data[amount_ix]
                if val != "" :
                    payload = {'query': val}
                    consulta_raw = requests.post(url, headers=headers, data=payload).text
                    consulta_dec = json.loads(consulta_raw)
                    if "foods" in consulta_dec:
                        calories_acum += consulta_dec["foods"][0]["nf_calories"]
                        fat_acum += consulta_dec["foods"][0]["nf_total_fat"]
                        protein_acum += consulta_dec["foods"][0]["nf_protein"]
                        sugar_acum += consulta_dec["foods"][0]["nf_sugars"]
                        carbs_acum += consulta_dec["foods"][0]["nf_total_carbohydrate"]
                        sat_fat_acum += consulta_dec["foods"][0]["nf_saturated_fat"]
                        fiber_acum += consulta_dec["foods"][0]["nf_dietary_fiber"]
                        sodium_acum += consulta_dec["foods"][0]["nf_sodium"]
                        ingredient_store = Ingredient(item=prev_item, name=form.cleaned_data[ingredient_ix],
                                                      amount=form.cleaned_data[amount_ix])
                        ingredient_store.save()

            prev_item.calories = calories_acum
            prev_item.tot_fat = fat_acum
            prev_item.tot_protein = protein_acum
            prev_item.sugar = sugar_acum
            prev_item.tot_carbs = carbs_acum
            prev_item.fat_saturated = sat_fat_acum
            prev_item.fiber = fiber_acum
            prev_item.sodium = sodium_acum
            prev_item.save()

            history_entry = History(usuario=user, item=prev_item, date_consumed=timezone.now())
            history_entry.save()
            return HttpResponseRedirect("/profile/" + user_id + "/history")

    else:
        form = IngredientsForm()  # Unbound form

    return render(request, 'app_1/ingredients_form.html', {'form': form, 'user_id': user_id, 'item_id': item_id})


def history(request, user_id):
    user_history = History.objects.filter(usuario=user_id)
    items_history = [] # list to be sent to the template
    history_entry = {} # dictionary to allocate Items with the day it was added
    macro_eaten = {} # information about the monthly intake of macronutrients
    calories_acum = 0 # acumulator for macro_eaten
    fat_acum = 0 # idem
    protein_acum = 0 # idem
    carbs_acum = 0 # idem
    for entry in user_history:
        # itearate through all the items in the history of <user_id> user
        history_entry["ITEM"] = Item.objects.get(pk=entry.item_id) # store the information in
        history_entry["DATE"] = entry.date_consumed                 # its convinient place in dict
        if entry.date_consumed.month == timezone.now().month and entry.date_consumed.year == timezone.now().year :  
            # if intake was this month we add its macronutrients to the acumulators
                calories_acum += history_entry["ITEM"].calories
                fat_acum += history_entry["ITEM"].tot_fat
                protein_acum += history_entry["ITEM"].tot_protein
                carbs_acum += history_entry["ITEM"].tot_carbs
        items_history.append(history_entry) # in any way we append to the list of history entries
        history_entry = {}  # reset for next iteration
        # set all entries of the monthly intake
        macro_eaten['cal'] = calories_acum 
        macro_eaten['carb'] = carbs_acum
        macro_eaten['prot'] = protein_acum
        macro_eaten['fat'] = fat_acum
    objectives = Objective.objects.get(usuario=user_id) # save the monthly objective of the user
    # now calculate the percentage of the intake over the objective
    macro_eaten['cal_p'] = (calories_acum * 100 ) / objectives.calories_obj 
    macro_eaten['carb_p'] = (carbs_acum * 100 ) / objectives.carbs_obj
    macro_eaten['prot_p'] = (protein_acum * 100 ) / objectives.protein_obj
    macro_eaten['fat_p'] = (fat_acum * 100 ) / objectives.fat_obj
    # setup the context
    context = {'items_history': items_history,'macro_eaten':macro_eaten,'user_objectives': objectives ,'user_id': user_id}
    return render(request, 'app_1/history.html', context)


def register(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            user = form.save()
            user.refresh_from_db()  # load the profile instance created by the signal
            # username = form.cleaned_data.get('username')
            user.profile.date_birth = form.cleaned_data.get('date_birth')
            user.profile.country = form.cleaned_data.get('country')
            user.profile.city = form.cleaned_data.get('city')
            user.profile.cp = form.cleaned_data.get('cp')
            user.profile.tags = form.cleaned_data.get('tags')
            user.save()
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=user.username, password=raw_password)
            login(request, user)
            return redirect('app_1:index')
    else:
        form = RegisterForm()
    return render(request, 'app_1/register.html', {'form': form})


def edit_profile(request, user_id):
    user = get_object_or_404(User, pk=user_id)

    if request.method == 'POST':
        user.first_name = request.POST.get('first_name', user.first_name)
        user.last_name = request.POST.get('last_name', user.last_name)
        user.email = request.POST.get('email', user.email)

        user.save()

    return render(request, 'app_1/profile.html', {'user': user})


def remove_user(request, user_id):
    profile = get_object_or_404(Profile, pk=user_id)
    if request.method == 'POST':
        profile.user.is_active = False
        profile.user.save()
        profile.save()

    return redirect('/')

MacroCalculator/app_1/templates/app_1/history.html
{% extends "base_generic.html" %}
{% block title %}History{% endblock %}
{% block content %}

{% load staticfiles %}

<script type="text/javascript">
  $(document).ready(function() {

    var table = $('#table1').DataTable({
        "dom": '<"top">rt<"bottom"p><"clear">',
		"order": [[ 5, "desc" ]],
		"pageLength": 50,
    });

/*
    jQuery("#buttonfilter").click(function(event){
    	event.preventDefault();
    	$("#dlDropDown").dropdown("toggle");
    	return false;
    });*/


	 jQuery("#namefilter").keyup(function () {
	     table
        .columns( 0 )
        .search( this.value )
        .draw();
	 });

});



</script>

<div class="container-fluid">

	<h2>Your history</h2>

	<div class="input-group">
		<div class="input-group-btn search-panel">
		   <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
				<span id="search_concept">Filter by</span> <span class="caret"></span>
		   </button>

			<div class="dropdown-menu" role="menu" style="width:600px !important;">
				<form>
					<div class="form-group form-inline">
						<label for="namefilter">Name: </label>
						<input id="namefilter" class="form-control" type="text" />
					</div>
				</form>
			</div>
		</div>
	</div>



	<table id="table1" class="table">
	 <thead>
	  <tr>
		  <th scope="col">Name</th>
		  <th scope="col">Calories</th>
		  <th scope="col">Carbohydrates</th>
		  <th scope="col">Proteins</th>
		  <th scope="col">Fats</th>
		  <th scope="col">Date</th>
		  <th scope="col">Actions</th>
	  </tr>
	 </thead>
	 <tbody>

	{% if items_history %}
	{% for dup in items_history %}
		<tr>
			<td><strong><a href="/profile/{{ user_id }}/history/item/{{ dup.ITEM.id }}" style="color: black">{{ dup.ITEM.name }}</a></strong></td>
			<td>{{ dup.ITEM.calories }}</td>
			<td>{{ dup.ITEM.tot_carbs|floatformat:2 }}</td>
			<td>{{ dup.ITEM.tot_protein|floatformat:2  }}</td>
			<td>{{ dup.ITEM.tot_fat|floatformat:2  }}</td>
			<td>{{ dup.DATE }}</td>
			<td><a href="/profile/{{ user_id }}/item/{{ dup.ITEM.id }}/delete">
				<img border="0" alt="delete food" src="{% static 'images/delete.png' %}" width="30" height="30    ">
			</a></td>
		</tr>
	{% endfor %}
	{% else %}
        <p><strong>NOTHING TO SHOW</strong></p>
    {% endif %}

	 </tbody>
	</table>
</div>
<div class="container-fluid">
    <h2>How well are you doing?</h2>
        <table id="table1" class="table">
            <thead>
                <tr>
                    <th scope="col">Macronutrient</th>
                    <th scope="col">Consumed</th>
                    <th scope="col">Objective</th>
                    <th scope="col">Percentage achieved</th>
                </tr>
            </thead>
            <tbody>
                {% if user_objectives %} 
                    <tr>
                        <td><strong></strong>Calories</td>
                        <td>{{ macro_eaten.cal|floatformat:2 }}</td>
                        <td>{{  user_objectives.calories_obj }}</td>
                        <td>{{ macro_eaten.cal_p|floatformat:2 }}%</td>
                    </tr>
                    <tr>
                        <td><strong>Carbohydrates</strong></td>
                        <td>{{ macro_eaten.carb|floatformat:2 }}</td>
                        <td>{{  user_objectives.carbs_obj }}</td>
                        <td>{{ macro_eaten.carb_p|floatformat:2 }}%</td>
                    </tr>
                    <tr>
                        <td><strong>Proteins</strong></td>
                        <td>{{ macro_eaten.prot|floatformat:2 }}</td>
                        <td>{{  user_objectives.protein_obj }}</td>
                        <td>{{ macro_eaten.prot_p|floatformat:2 }}%</td>
                    </tr>
                    <tr>
                        <td><strong>Fats</strong></td>
                        <td>{{ macro_eaten.fat|floatformat:2 }}</td>
                        <td>{{  user_objectives.fat_obj }}</td>
                        <td>{{ macro_eaten.fat_p|floatformat:2 }}%</td>
                    </tr>
                {% else %}
                    <p><strong>NOTHING TO SHOW</strong></p>
                {% endif %}
            </tbody>
        </table>
</div>
<div>
    
</div>


{% endblock %}

MacroCalculator/app_1/templates/app_1/home.html
{% extends "base_generic.html" %}
{% block title %}MacroCalculator{% endblock %}
{% block content %}
<h2>MacroCalculator</h2>
<a href="{% url 'app_1:register' %}">Register</a>
<a href="{% url 'app_1:login' %}">Log in</a>
{% endblock %}

MacroCalculator/app_1/templates/app_1/ingredients_form.html
{% extends "base_generic.html" %}
{% block title %}Add ingredient{% endblock %}
{% block content %}
<form action="/profile/{{user_id}}/add_food/{{item_id}}/add_ingredient" method="post">
    {% csrf_token %}
    {{ form.non_field_errors }}
	<div class="fieldWrapper">
    	{{ form.subject.errors }}
    	<label for="{{ form.subject.id_for_label }}">Ingredient 1:</label>
    	{{ form.ingredient_1 }}
    	{{ form.message.errors }}
    	<label for="{{ form.message.id_for_label }}">Amount 1:</label>
    	{{ form.amount_1 }}
	</div>
	<div class="fieldWrapper">
    	{{ form.subject.errors }}
    	<label for="{{ form.subject.id_for_label }}">Ingredient 2:</label>
    	{{ form.ingredient_2 }}
    	{{ form.message.errors }}
    	<label for="{{ form.message.id_for_label }}">Amount 2:</label>
    	{{ form.amount_2 }}
	</div>
	<div class="fieldWrapper">
    	{{ form.subject.errors }}
    	<label for="{{ form.subject.id_for_label }}">Ingredient 3:</label>
    	{{ form.ingredient_3 }}
    	{{ form.message.errors }}
    	<label for="{{ form.message.id_for_label }}">Amount 3:</label>
    	{{ form.amount_3 }}
	</div>
	<div class="fieldWrapper">
    	{{ form.subject.errors }}
    	<label for="{{ form.subject.id_for_label }}">Ingredient 4:</label>
    	{{ form.ingredient_4 }}
    	{{ form.message.errors }}
    	<label for="{{ form.message.id_for_label }}">Amount 4:</label>
    	{{ form.amount_4 }}
	</div>
	<div class="fieldWrapper">
    	{{ form.subject.errors }}
    	<label for="{{ form.subject.id_for_label }}">Ingredient 5:</label>
    	{{ form.ingredient_5 }}
    	{{ form.message.errors }}
    	<label for="{{ form.message.id_for_label }}">Amount 5:</label>
    	{{ form.amount_5 }}
	</div>
	<div class="fieldWrapper">
    	{{ form.subject.errors }}
    	<label for="{{ form.subject.id_for_label }}">Ingredient 6:</label>
    	{{ form.ingredient_6 }}
    	{{ form.message.errors }}
    	<label for="{{ form.message.id_for_label }}">Amount 6:</label>
    	{{ form.amount_6 }}
	</div>
	<div class="fieldWrapper">
    	{{ form.subject.errors }}
    	<label for="{{ form.subject.id_for_label }}">Ingredient 7:</label>
    	{{ form.ingredient_7 }}
    	{{ form.message.errors }}
    	<label for="{{ form.message.id_for_label }}">Amount 7:</label>
    	{{ form.amount_7 }}
	</div>
	<div class="fieldWrapper">
    	{{ form.subject.errors }}
    	<label for="{{ form.subject.id_for_label }}">Ingredient 8:</label>
    	{{ form.ingredient_8 }}
    	{{ form.message.errors }}
    	<label for="{{ form.message.id_for_label }}">Amount 8:</label>
    	{{ form.amount_8 }}
	</div>
	<div class="fieldWrapper">
    	{{ form.subject.errors }}
    	<label for="{{ form.subject.id_for_label }}">Ingredient 9:</label>
    	{{ form.ingredient_9 }}
    	{{ form.message.errors }}
    	<label for="{{ form.message.id_for_label }}">Amount 9:</label>
    	{{ form.amount_9 }}
	</div>
	<div class="fieldWrapper">
    	{{ form.subject.errors }}
    	<label for="{{ form.subject.id_for_label }}">Ingredient 10:</label>
    	{{ form.ingredient_10 }}
    	{{ form.message.errors }}
    	<label for="{{ form.message.id_for_label }}">Amount 10:</label>
    	{{ form.amount_10 }}
	</div>
	<input type="submit" value="Submit">
</form>
{% endblock %}

MacroCalculator/app_1/templates/app_1/item_form.html
{% extends "base_generic.html" %}
{% block title %}Add food{% endblock %}
{% block content %}
<form action="/profile/{{user_id}}/add_food/" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Submit" />
</form>
{% endblock %}

MacroCalculator/app_1/templates/app_1/login.html
{% extends "base_generic.html" %}
{% block title %}Log in{% endblock %}
{% block content %}
<h2>Login</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Login</button>
  </form>
{% endblock %}

MacroCalculator/app_1/templates/app_1/profile.html
{% extends "base_generic.html" %}

{% block content %}
<form action="." method="post">
    {% csrf_token %}
    <div class="form-group">
        <label class="control-label col-sm-2" for="id_first_name">First name:</label>
        <div class="col-sm-10">
            <input class="form-control" name="first_name" id="id_first_name" maxlength="30" type="text" value="{{user.first_name}}">
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-sm-2" for="id_last_name">Last name:</label>
        <div class="col-sm-10">
            <input class="form-control" name="last_name" id="id_last_name" maxlength="30" type="text" value="{{user.last_name}}">
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-sm-2" for="id_first_name">Email:</label>
        <div class="col-sm-10">
            <input class="form-control" name="email" id="id_email" maxlength="254" type="email" value="{{user.email}}">
        </div>
    </div>

    <button type="submit">Update Profile</button>
</form>

{% endblock %}

MacroCalculator/app_1/templates/app_1/register.html
{% extends "base_generic.html" %}
{% block title %}Register{% endblock %}
{% block content %}
<h2>Sign up</h2>
<form method="post">
  {% csrf_token %}
    {% for field in form %}
      <p>
        {{ field.label_tag }}<br>
        {{ field }}
        {% if field.help_text %}
          <small style="color: grey">{{ field.help_text }}</small>
        {% endif %}
        {% for error in field.errors %}
          <p style="color: red">{{ error }}</p>
        {% endfor %}
      </p>
    {% endfor %}
    <button type="submit">Sign up</button>
</form>
{% endblock %}

MacroCalculator/app_1/templates/app_1/user_prof.html
<!-- user.id -> id de la URL; request.user.id -> id del usuario con sesión iniciada-->

{% extends "base_generic.html" %}
{% block title %}Profile{% endblock %}
{% block content %}
<div class="container">
    <div class="col-sm-12 text-center">
        <h2>{{ user.username }}'s profile</h2>
    </div>

    <p>Name: {{user.first_name}} </p>
    <p>Last name: {{user.last_name}} </p>
    <p>Email: {{user.email}} </p>
    <p>Birth date: {{user.profile.date_birth}} </p>
    <p>Country: {{user.profile.country}} </p>
    <p>City: {{user.profile.city}} </p>
    <p>Zip code: {{user.profile.cp}} </p>
    <p>Tags: {{user.profile.tags}} </p>
    <p><a href="objective">Objectives</a></p>
    <p><a href="add_food">Add food</a></p>
    <p><a href="history">History</a></p>
</div>

<div class="container-fluid">
    <form action="/profile/{{user.id}}/modify_profile" method="get">
        {% csrf_token %}
        <button type="submit" class="btn btn-default">Modify profile</button>
    </form>

    <form action="/profile/{{user.id}}/remove_user" method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-default">Remove User</button>
    </form>

</div>
{% endblock %}